name: Build RPI

on: [push]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}
    steps:
   
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - uses: pguyot/arm-runner-action@v2.3.1 
      id: build_image
      with:
        base_image: raspios_lite:latest
        image_additional_mb: 4000
        bind_mount_repository: true
        import_github_env: true
        commands: |
            ls -a
            curl -1sLf \
            'https://dl.cloudsmith.io/public/openhd/openhd-2-2-evo/setup.deb.sh' \
            | sudo -E bash
            sudo apt update
            sudo apt remove -y libcamera*
            apt install -y libcamera-openhd libdrm-dev
            echo "debug cam install"
            sudo apt install -y libboost-dev git python3-pip ruby-dev 
            sudo apt install -y libgnutls28-dev openssl libtiff5-dev qtbase5-dev libqt5core5a libqt5gui5 libqt5widgets5 
            sudo apt install -y meson libegl1-mesa-dev cmake libboost-program-options-dev libdrm-dev libexif-dev libegl1-mesa-dev
            sudo pip3 install pyyaml ply jinja2
            sudo pip3 install --upgrade meson
            gem install fpm
            sudo apt install -y libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev libcamera-openhd
            meson build
            cd build
            meson configure -Dpipelines=raspberrypi -Dtest=false
            cd ..
            ninja -C build
            mkdir build
            cd build
            cmake ..
            DESTDIR=/opt/libcamera-apps-openhd
            make -j4
        
            fpm -a armhf -s dir -t deb -n libcamera-apps -v 10.1 -C /opt/libcamera-apps-openhd -p libcamera-apps_VERSION_ARCH.deb

    - name: Upload to Github
      uses: 'actions/upload-artifact@v2'
      with:
        name: "libcamera"
        path: |
          /*.deb
          *deb
          *.log


    - name: Push
      id: push
      uses: cloudsmith-io/action@master
      with:
        api-key: ${{ secrets.CLOUDSMITH_API_KEY }}
        command: "push"
        format: "deb"
        owner: "openhd"
        repo: "openhd-2-2-evo"
        distro: "raspbian"
        release: "bullseye"
        republish: "true" # needed ONLY if version is not changing
        file: "*deb"


      #- name: Install
      #  run: |
      #    cd OpenHD/build
      #    sudo cmake --install .
      #- name: Build ninja
      #  run: |
      #    sudo apt -y install ninja-build
      #    cd OpenHD
      #    ./build_cmake.sh
